version: '3.8'
services:
  davinci:
    build: .
    image: davinci:1.0
    container_name: bi
    restart: always
    depends_on:
      - chrome
    ports:
      - 60010:8080
    environment:
      SCREENSHOT_REMOTE_WEBDRIVER_URL: http://chrome:4444/wd/hub
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/additional.yml:/opt/davinci/config/additional.yml
  chrome:
    image: selenium/standalone-chrome
    shm_size: 2g
    environment:
      - TZ=Asia/Shanghai
